### ISSUE TITLE
Implement projections

### ISSUE THREAD

**Issue by lmullen** [ropensci/cartographer#2]

**Comment by jhollist** [comment]
Just wanted to leave a +1 for this.  How were you thinking of doing this? I know next to nothing about d3, but did see that [projections are supported](https://github.com/mbostock/d3/wiki/Geo-Projections).  Being able to map data in projected coordinates, instead of converting to geographic would be a fantastic addition! 

I'd be willing to help out how I can, but am afraid I'd have a huge learning curve on the d3 stuff just to get to a point of minimal usefulness...

**Comment by lmullen** [comment]
I'll add a function `projection()` or the like which will let you select from the d3 projections.

**Comment by jhollist** [comment]
Thanks for the reply.    Does d3 require that input data are in geographic coords and then projects them when the map gets rendered? If so, how would you map data that are already in projected coordinates?

**Comment by lmullen** [comment]
Yes, d3 takes geographic coordinates and then projects them. I haven't
decided what types of input to support yet. So far it includes points as
latitudes and longitudes in a data frame, and GeoJSON/TopoJSON polygons.
I'll add at least a few more. But as of now I don't have any intention of
supporting projected coordinates for points. A user could take those
points, reproject (or deproject them, I suppose) to latitude and longitude,
and then plot them with cartographer.

Do you have a specific use case in mind? I'll consider implementing it if
it would be generally useful.

**Comment by jhollist** [comment]
I do a lot of GIS with R.  Only thing that is missing is easy visualization of the results.  So I would want to be able to display multiple layers (raster, poly, lines, points...) that are more often than not projected (Albers USA for much of the data I use) and be able to zoom, pan, and identify.  D3 seems to be a good solution for the functionality, but (de)projecting is a bit of an issue.   

I have been playing with getting some of this working via the default plotting functions for sp and raster objects plus the zoom package.  Minimal success so far so I keep going back to the various javascript solutions.

**Comment by lmullen** [comment]
Pardon me if you already know about this, but have you tried the
sp::spTransform() function to reproject objects with classes from the sp
package to WGS84?

I intend to support plotting of the various sp classes, and perhaps it will
be possible to check their projection and deproject them automatically.
I'll have to think about it.

Thanks for letting me know about you use case.

**Comment by jhollist** [comment]
thanks.  I do know about sp::spTransform().  This would work, but my main concern with always having to deproject the original data is performance.  I work with raster data in Albers fairly frequently and having to convert those back to wgs84 can take a lot of time, plus the data need to get interpolated.  So what would be displayed would not be the same data as the original input.  

I did spend some time (productive Snow Days, for me!) and got my use case more or less implemented with a [`quickmapr`](https://github.com/jhollist/quickmapr).  This allows me to use my normal workflow and be able to interact with the resultant data quickly.  

I could see using something like `cartographer` after my anlaysis workflow was determined to imbed interactive maps in shiny,Rmd's etc.  At that point the deprojecting of the sp classes wouldn't be a big issue because it would happen just the once for rendering the final map.

Thanks for thinking about this and I still agree with my +1 for the projecting functions.  Still think it has a lot of utility.
